confluent.controlcenter.data.dir=/tmp/confluent/control-center

confluent.controlcenter.ui.autoupdate.enable=true
confluent.controlcenter.usage.data.collection.enable=true

bootstrap.servers=localhost:9092
zookeeper.connect=localhost:2181
confluent.controlcenter.kafka.AK1.bootstrap.servers=localhost:9093
confluent.controlcenter.kafka.AK1.zookeeper.connect=localhost:2182
confluent.controlcenter.streams.cprest.url=http://0.0.0.0:8090
confluent.controlcenter.schema.registry.url=http://localhost:8081
confluent.controlcenter.schema.registry.basic.auth.credentials.source=USER_INFO
confluent.controlcenter.schema.registry.basic.auth.user.info=fred:letmein
confluent.controlcenter.kafka.AK1.cprest.url=http://0.0.0.0:8091
confluent.controlcenter.schema.registry.SR-AK1.url=http://localhost:8082
confluent.controlcenter.schema.registry.SR-AK1.basic.auth.credentials.source=USER_INFO
confluent.controlcenter.schema.registry.SR-AK1.basic.auth.user.info=fred:letmein


confluent.controlcenter.internal.topics.replication=1
confluent.controlcenter.command.topic.replication=1
confluent.monitoring.interceptor.topic.replication=1
confluent.metrics.topic.replication=1
